# Generated by Django 3.1.5 on 2021-01-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gos', '0003_auto_20210118_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='encountermonster',
            name='current_hp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='hit_points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
