# Generated by Django 3.1.5 on 2021-01-17 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('index', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EncounterPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos.encounter')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos.player')),
            ],
        ),
        migrations.CreateModel(
            name='EncounterMonster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiative', models.IntegerField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos.encounter')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gos.monster')),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='monsters',
            field=models.ManyToManyField(through='gos.EncounterMonster', to='gos.Monster'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='players',
            field=models.ManyToManyField(through='gos.EncounterPlayer', to='gos.Player'),
        ),
    ]
